# Generated by Django 3.1.7 on 2021-03-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("SGD", "Singapore Dollar"),
                            ("USD", "US Dollar"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_value", models.FloatField(default=0.0)),
                ("notes", models.TextField()),
            ],
        ),
    ]
