# Generated by Django 3.1.7 on 2021-03-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_share"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="total_value",
            new_name="num_shares",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="stockasset",
            name="share_price",
        ),
        migrations.RemoveField(
            model_name="stockasset",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="stockasset",
            name="symbol",
        ),
        migrations.AddField(
            model_name="asset",
            name="share",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.share"
            ),
            preserve_default=False,
        ),
    ]
